# The Duralki configs.
duralki:
  # The CraftEngine Item ID.
  item-id: "neom:duralki"
  # How much durability will transfer per tick?
  transferrate: 20
  # Sounds - self explanatory.
  break-sound: "miecraft:entity.item.break"
  transfer-sound: "minecraft:block.amethyst_block.chime"
  replace-sound: "minecraft:block.end_portal_frame.fill"
  # Blacklist of items that will not be drillable (Minecraft and CraftEngine Item IDs).
  blacklisted-tools: [
    "neom:gauntlet"
  ]
  replace-tools:
    "neom:gauntlet": "minecraft:diamond_pickaxe"


# The Gauntlet configs.
gauntlet:
  # The CraftEngine Item ID.
  item-id: "neom:gauntlet"
  # The Mana recharge period in ticks.
  mana-recharge-period: 20
  # The amount of mana recharge per period.
  mana-per-period: 1
  # The amount of mana consumed per break.
  mana-consume: 5
  # The amount of mana capacity lost at default.
  default-mana-capacity-los: 10
  # The amount of mana capacity lost per break.
  mana-capacity-los-per-break: 0.1
  # The cooldown in seconds for the mana regen after breaking a block.
  cooldown: 10
  # The blocks that can be drilled.
  drillable-blocks:
    - "miecraft:stone"
    - "minecraft:cobblestone"
    - "minecraft:tuff"
    - "minecraft:infested_stone"
    - "minecraft:granite"
    - "minecraft:diorite"
    - "minecraft:andesite"

# The Biom changer configs.
biomchanger:
  # First the CraftEngine Item ID second the biom id.
  items:
    "custom:item": "minecraft:jungle"
    "custom:item2": "minecraft:jungle"
  # Radius of the biom change.
  radius: 15
  # Should the items be removed from the inventory?
  removeItems: true
  # List of players that can use the biom changer.
  players:
    - "bfd59ae0-c905-4f3b-903a-3ce8510d6b71"