# The Duralki configs.
duralki:
  # The CraftEngine Item ID.
  item-id: "neom:duralki"
  # How much durability will transfer per tick?
  transferrate: 20
  # Sounds - self explanatory.
  break-sound: ENTITY_ITEM_BREAK
  transfer-sound: BLOCK_AMETHYST_BLOCK_CHIME
  # Blacklist of items that will not be drillable (Minecraft and CraftEngine Item IDs).
  blacklisted-tools: [
    "neom:gauntlet"
  ]

# The Gauntlet configs.
gauntlet:
  # The CraftEngine Item ID.
  item-id: "neom:gauntlet"
  # The Mana recharge period in ticks.
  mana-recharge-period: 20
  # The amount of mana recharge per period.
  mana-per-period: 1
  # The amount of mana consumed per break.
  mana-consume: 5
  # The amount of mana capacity lost at default.
  default-mana-capacity-los: 10
  # The amount of mana capacity lost per break.
  mana-capacity-los-per-break: 0.1
  # The cooldown in seconds for the mana regen after breaking a block.
  cooldown: 10
  # The blocks that can be drilled.
  drillable-blocks:
    - "miecraft:stone"
    - "minecraft:cobblestone"
    - "minecraft:tuff"
    - "minecraft:infested_stone"
    - "minecraft:granite"
    - "minecraft:diorite"
    - "minecraft:andesite"